[package]
name = "digifi"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6" # MIT or Apache 2.0
nalgebra = "0.33.0" # Apache 2.0
num = "0.4" # MIT or Apache 2.0
csv = "1.3.0" # Unlicense or MIT