[package]
name = "digifi"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
# Only used for use ndarray_linalg::Inverse;
ndarray-linalg = { version = "0.16.0", features = ["intel-mkl"] }
num = "0.4"
csv = "1.3.0"